### ISSUE TITLE
Seems the deployment is gone?

### ISSUE THREAD

**Issue by HurricanKai** [Youssef1313/DotNetSyntaxTreeVisualizer#18]
I unfortunately can't reach https://dotnetsyntaxtreevisualizer.azurewebsites.net/ anymore

**Comment by Youssef1313** [comment]
@HurricanKai Unfortunately, my Azure subscription has ended. I'll try to get it renewed soon.

**Comment by Youssef1313** [comment]
It's working now @HurricanKai :tada:

**Comment by HurricanKai** [comment]
Thanks :tada:
